import type { GainMapResolutionMode, HdrGainMapControls, HdrPresetId } from './types'

export const defaultPresetId: HdrPresetId = 'natural'

export const defaultHdrGainMapControls: HdrGainMapControls = {
  preset: defaultPresetId,
  hdrStrengthStops: 1.2,
  highlightStartPct: 95.0,
  highlightRolloffPct: 99.7,
  shadowLift: 0.15,
  colorProtect: 0.85,
  detail: 0.12,
  headroomStops: 2.0,
  midtoneLock: 0.6,
  whitePointGuardPct: 99.8,
  blackPointGuardPct: 0.2,
  edgeAwareRadius: 8,
  edgeAwareEps: 0.001,
  clipGuard: 0.85,
  gainMapGamma: 1.0,
  gainMapResolutionMode: 'auto',
}

export const hdrPresets: Record<HdrPresetId, HdrGainMapControls> = {
  natural: {
    ...defaultHdrGainMapControls,
    preset: 'natural',
  },
  bright: {
    preset: 'bright',
    hdrStrengthStops: 1.8,
    highlightStartPct: 92.0,
    highlightRolloffPct: 99.5,
    shadowLift: 0.3,
    colorProtect: 0.75,
    detail: 0.18,
    headroomStops: 2.5,
    midtoneLock: 0.45,
    whitePointGuardPct: 99.7,
    blackPointGuardPct: 0.25,
    edgeAwareRadius: 8,
    edgeAwareEps: 0.0012,
    clipGuard: 0.75,
    gainMapGamma: 1.04,
    gainMapResolutionMode: 'auto',
  },
  neonNight: {
    preset: 'neonNight',
    hdrStrengthStops: 2.2,
    highlightStartPct: 90.0,
    highlightRolloffPct: 99.8,
    shadowLift: 0.22,
    colorProtect: 0.9,
    detail: 0.22,
    headroomStops: 3.0,
    midtoneLock: 0.7,
    whitePointGuardPct: 99.85,
    blackPointGuardPct: 0.1,
    edgeAwareRadius: 6,
    edgeAwareEps: 0.0008,
    clipGuard: 0.8,
    gainMapGamma: 1.08,
    gainMapResolutionMode: 'auto',
  },
  soft: {
    preset: 'soft',
    hdrStrengthStops: 1.5,
    highlightStartPct: 94.0,
    highlightRolloffPct: 99.6,
    shadowLift: 0.18,
    colorProtect: 0.8,
    detail: 0.05,
    headroomStops: 2.2,
    midtoneLock: 0.6,
    whitePointGuardPct: 99.75,
    blackPointGuardPct: 0.2,
    edgeAwareRadius: 14,
    edgeAwareEps: 0.0015,
    clipGuard: 0.85,
    gainMapGamma: 0.96,
    gainMapResolutionMode: 'auto',
  },
  product: {
    preset: 'product',
    hdrStrengthStops: 1.0,
    highlightStartPct: 97.0,
    highlightRolloffPct: 99.9,
    shadowLift: 0.08,
    colorProtect: 0.95,
    detail: 0.06,
    headroomStops: 1.8,
    midtoneLock: 0.75,
    whitePointGuardPct: 99.92,
    blackPointGuardPct: 0.15,
    edgeAwareRadius: 6,
    edgeAwareEps: 0.0008,
    clipGuard: 0.9,
    gainMapGamma: 1.0,
    gainMapResolutionMode: 'auto',
  },
}

export const defaultBypassOptions = hdrPresets[defaultPresetId]

export const gainMapResolutionModes: GainMapResolutionMode[] = [
  'auto',
  '480p',
  '720p',
  '1080p',
  'quarter',
  'half',
  'full',
  'custom',
]
